<?php

namespace ContainerTUPkBHR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LEQslOeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LEQslOe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LEQslOe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IngredientController::delete' => ['privates', '.service_locator.G0UfuGH', 'get_ServiceLocator_G0UfuGHService', true],
            'App\\Controller\\IngredientController::edit' => ['privates', '.service_locator.G0UfuGH', 'get_ServiceLocator_G0UfuGHService', true],
            'App\\Controller\\IngredientController::index' => ['privates', '.service_locator.cwiUHKK', 'get_ServiceLocator_CwiUHKKService', true],
            'App\\Controller\\IngredientController::new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\RecipeController::delete' => ['privates', '.service_locator.gA9ZvFz', 'get_ServiceLocator_GA9ZvFzService', true],
            'App\\Controller\\RecipeController::edit' => ['privates', '.service_locator.gA9ZvFz', 'get_ServiceLocator_GA9ZvFzService', true],
            'App\\Controller\\RecipeController::index' => ['privates', '.service_locator.zyBuAUC', 'get_ServiceLocator_ZyBuAUCService', true],
            'App\\Controller\\RecipeController::new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.hcYvfFK', 'get_ServiceLocator_HcYvfFKService', true],
            'App\\Controller\\UserController::editPassword' => ['privates', '.service_locator.hcYvfFK', 'get_ServiceLocator_HcYvfFKService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\IngredientController:delete' => ['privates', '.service_locator.G0UfuGH', 'get_ServiceLocator_G0UfuGHService', true],
            'App\\Controller\\IngredientController:edit' => ['privates', '.service_locator.G0UfuGH', 'get_ServiceLocator_G0UfuGHService', true],
            'App\\Controller\\IngredientController:index' => ['privates', '.service_locator.cwiUHKK', 'get_ServiceLocator_CwiUHKKService', true],
            'App\\Controller\\IngredientController:new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\RecipeController:delete' => ['privates', '.service_locator.gA9ZvFz', 'get_ServiceLocator_GA9ZvFzService', true],
            'App\\Controller\\RecipeController:edit' => ['privates', '.service_locator.gA9ZvFz', 'get_ServiceLocator_GA9ZvFzService', true],
            'App\\Controller\\RecipeController:index' => ['privates', '.service_locator.zyBuAUC', 'get_ServiceLocator_ZyBuAUCService', true],
            'App\\Controller\\RecipeController:new' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.hcYvfFK', 'get_ServiceLocator_HcYvfFKService', true],
            'App\\Controller\\UserController:editPassword' => ['privates', '.service_locator.hcYvfFK', 'get_ServiceLocator_HcYvfFKService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\IngredientController::delete' => '?',
            'App\\Controller\\IngredientController::edit' => '?',
            'App\\Controller\\IngredientController::index' => '?',
            'App\\Controller\\IngredientController::new' => '?',
            'App\\Controller\\RecipeController::delete' => '?',
            'App\\Controller\\RecipeController::edit' => '?',
            'App\\Controller\\RecipeController::index' => '?',
            'App\\Controller\\RecipeController::new' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::editPassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\IngredientController:delete' => '?',
            'App\\Controller\\IngredientController:edit' => '?',
            'App\\Controller\\IngredientController:index' => '?',
            'App\\Controller\\IngredientController:new' => '?',
            'App\\Controller\\RecipeController:delete' => '?',
            'App\\Controller\\RecipeController:edit' => '?',
            'App\\Controller\\RecipeController:index' => '?',
            'App\\Controller\\RecipeController:new' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:editPassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
