<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFbTxjit\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFbTxjit/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFbTxjit.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFbTxjit\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFbTxjit\App_KernelDevDebugContainer([
    'container.build_hash' => 'FbTxjit',
    'container.build_id' => 'cd7d1bed',
    'container.build_time' => 1693431581,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFbTxjit');
