<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8imPsHA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8imPsHA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8imPsHA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8imPsHA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8imPsHA\App_KernelDevDebugContainer([
    'container.build_hash' => '8imPsHA',
    'container.build_id' => 'b2473fd2',
    'container.build_time' => 1694462378,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8imPsHA');
