<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9GYKTcx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9GYKTcx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9GYKTcx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9GYKTcx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9GYKTcx\App_KernelDevDebugContainer([
    'container.build_hash' => '9GYKTcx',
    'container.build_id' => 'e8930408',
    'container.build_time' => 1694432566,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9GYKTcx');
