<?php

namespace ContainerDRR8rHm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DLz4IBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d_lz4IB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d_lz4IB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\IngredientController::delete' => ['privates', '.service_locator.o.aN3J9', 'get_ServiceLocator_O_AN3J9Service', true],
            'App\\Controller\\IngredientController::edit' => ['privates', '.service_locator.o.aN3J9', 'get_ServiceLocator_O_AN3J9Service', true],
            'App\\Controller\\IngredientController::index' => ['privates', '.service_locator.7FZkCkl', 'get_ServiceLocator_7FZkCklService', true],
            'App\\Controller\\IngredientController::new' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\RecipeController::delete' => ['privates', '.service_locator.6gtTwgq', 'get_ServiceLocator_6gtTwgqService', true],
            'App\\Controller\\RecipeController::edit' => ['privates', '.service_locator.6gtTwgq', 'get_ServiceLocator_6gtTwgqService', true],
            'App\\Controller\\RecipeController::index' => ['privates', '.service_locator.6nHral7', 'get_ServiceLocator_6nHral7Service', true],
            'App\\Controller\\RecipeController::new' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.rYCEKpN', 'get_ServiceLocator_RYCEKpNService', true],
            'App\\Controller\\UserController::editPassword' => ['privates', '.service_locator.rYCEKpN', 'get_ServiceLocator_RYCEKpNService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\IngredientController:delete' => ['privates', '.service_locator.o.aN3J9', 'get_ServiceLocator_O_AN3J9Service', true],
            'App\\Controller\\IngredientController:edit' => ['privates', '.service_locator.o.aN3J9', 'get_ServiceLocator_O_AN3J9Service', true],
            'App\\Controller\\IngredientController:index' => ['privates', '.service_locator.7FZkCkl', 'get_ServiceLocator_7FZkCklService', true],
            'App\\Controller\\IngredientController:new' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\RecipeController:delete' => ['privates', '.service_locator.6gtTwgq', 'get_ServiceLocator_6gtTwgqService', true],
            'App\\Controller\\RecipeController:edit' => ['privates', '.service_locator.6gtTwgq', 'get_ServiceLocator_6gtTwgqService', true],
            'App\\Controller\\RecipeController:index' => ['privates', '.service_locator.6nHral7', 'get_ServiceLocator_6nHral7Service', true],
            'App\\Controller\\RecipeController:new' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.tgVVt0z', 'get_ServiceLocator_TgVVt0zService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.rYCEKpN', 'get_ServiceLocator_RYCEKpNService', true],
            'App\\Controller\\UserController:editPassword' => ['privates', '.service_locator.rYCEKpN', 'get_ServiceLocator_RYCEKpNService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\IngredientController::delete' => '?',
            'App\\Controller\\IngredientController::edit' => '?',
            'App\\Controller\\IngredientController::index' => '?',
            'App\\Controller\\IngredientController::new' => '?',
            'App\\Controller\\RecipeController::delete' => '?',
            'App\\Controller\\RecipeController::edit' => '?',
            'App\\Controller\\RecipeController::index' => '?',
            'App\\Controller\\RecipeController::new' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::editPassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\IngredientController:delete' => '?',
            'App\\Controller\\IngredientController:edit' => '?',
            'App\\Controller\\IngredientController:index' => '?',
            'App\\Controller\\IngredientController:new' => '?',
            'App\\Controller\\RecipeController:delete' => '?',
            'App\\Controller\\RecipeController:edit' => '?',
            'App\\Controller\\RecipeController:index' => '?',
            'App\\Controller\\RecipeController:new' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:editPassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
